### ISSUE TITLE
Endre hjelpetekster i Protokoll

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/records-of-processing-activities-gui#103]
- [x] Endre: "Kontaktpunkt" under Felles behandlingsansvar #3129

- [x] Endre: hjelpetekst for Felles behandlingsansvar #3065

- [x] Endre. legg til ny setning i hjelpetekst på Databehandler og databehandleravtaler #3063

- [x] Feil: mangler "er" i hjelpetekst på Databehandlere og databehandleravtaler #3062

- [x] Feil: hjelpetekst Daglig behandlingsansvar #3060

- [x] Feil: overskrift Daglig behandlingsanvar #3059

- [x] Endre: hjelpetekst i "Kategorier av registrerte" #3056

- [x] Endring: endre feltnavn og hjelpetekst på "formålet med behandlingsaktivitetene". #3055

- [x] Endre: hjelpetekst for Planlagte tidsfrister for sletting #3130

**Comment by lillelars** [comment]
testet i prod. ferdigstilt
