### ISSUE TITLE
Daglig behandlingsansvar: registrere to eller flere personer

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/records-of-processing-activities-gui#107]
- [x] Utvide slik at man kan legge til flere behandlingsansvarlige m/ tilhørende felter

- [x] Legge til slette funksjonalitet

- [x] Oppdatere Rapportsiden slik at flere behandlingsansvarlige m/ tilhørende felter vises her.

- [x] Tilpasse backend

Hentet fra behov:
https://github.com/Informasjonsforvaltning/behov/issues/474
Som: behandlingsansvarlig
Ønsker jeg å: kunne registrere kontaktopplysninger til alle i virksomheten som har fått delegert oppgaver som gjelder behandling av personopplysninger (daglig behandlingsansvar)
Slik at: jeg får full oversikt over hvem som er delegert daglig behandlingsansvar

NB! Må sjekke om brukerhistorien har sammenheng med Bergen kommune sitt ønske om å kunne registrere flere protokoller per virksomhet.

Relatert til epos:

Lenke til design: https://eggedosis.github.io/fdk-design/redirects/register/protocol/github474.html
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

Akseptansekriterier:

skal være mulig å legge til flere behandlingsansvarlige med alle tre feltene (navn, epost og telefon)
Skal være mulig å slette behandlingsansvarlig
NB! Dette må også vises i rapporten av behandlingsaktiviteter dersom det er flere enn en behandlingsansvarlig.

**Comment by lillelars** [comment]
@joebrreg har testet denne - ser bra ut. Klar for akseptanse.

**Comment by joebrreg** [comment]
@lillelars jeg godkjenner, men vi burde ta tekstendringene også før de går videre i behovsprosessen.
