### ISSUE TITLE
Titler og hjelpetekster i behandlingsaktiviteter:

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/records-of-processing-activities-gui#83]
- [x] endre tittel i henvisning til rettslig forpliktelse: https://github.com/Informasjonsforvaltning/fdk/issues/3083

- [x] Endre tekst i Kategorier av personopplysninger https://github.com/Informasjonsforvaltning/fdk/issues/3080

- [x] Endre tekstfelt som dukker opp når artikkel 10 er huket av
https://github.com/Informasjonsforvaltning/fdk/issues/3079

- [x] https://github.com/Informasjonsforvaltning/fdk/issues/3078 (trenger hjelp til å legge på otherArticlesDescription korrekt sted med pil)
Under: Behandlingsansvarlig --> " hjelpetekst under -> "Representant for behandlingsansvarlig":
Ved klikk på pil for å vise mer, skal dette vises:
Les mer på [Datatilsynets sider](https://www.datatilsynet.no/rettigheter-og-plikter/virksomhetenes-plikter/behandlingsgrunnlag/veileder-om-behandlingsgrunnlag/?id=10832)

![image](https://user-images.githubusercontent.com/39513382/82319648-39cadf00-99d2-11ea-9426-9a14ec32e98b.png)

- [x] https://github.com/Informasjonsforvaltning/fdk/issues/3074

- [x] https://github.com/Informasjonsforvaltning/fdk/issues/3073

- [x] https://github.com/Informasjonsforvaltning/fdk/issues/3070 -- Fjerne tekst "eller databehandler"
![image](https://user-images.githubusercontent.com/39513382/82319808-86aeb580-99d2-11ea-8647-a341614c1891.png)

- [x] https://github.com/Informasjonsforvaltning/fdk/issues/3066 (mulig tittel også skal endres i tillegg til felt)

- [x] Under: "Daglig behandlingsanvar"
Endre overskrift "kontaktpunkt" til "Navn på behandlingsansvarlig"

**Comment by lillelars** [comment]
Testet og godkjent. Mangler to av punktene - som blir håndtert i egne issues.
